version: "0.1"
services:
  spring-app:
    build: .
    container_name: myapp
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1111
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: unless-stopped
    networks:
      - appnet

  postgres:
    image: "postgres:17"
    container_name: mypostgres
    environment:
      - POSTGRES_PASSWORD=1111
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - appnet
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  appnet:
    name: appnet
    driver: bridge